name: amd64-docker

on:
  workflow_dispatch:
    inputs:
      profile:
        description: "ROOTFS 分区大小 (MB)"
        required: true
        default: "1024"
      include_docker:
        description: "是否包含 Dockerman UI (yes/no)"
        required: true
        default: "yes"
      enable_pppoe:
        description: "是否启用 PPPoE 配置 (yes/no)"
        required: true
        default: "no"
      custom_packages:
        description: "追加/移除的软件包，留空为默认"
        required: false
        default: ""
      docker_push:
        description: "是否推送 Docker 镜像到 Docker Hub"
        required: true
        default: "false"
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install image dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-utils genisoimage

      - name: Sanitize PATH
        run: |
          CLEAN_PATH=$(printf '%s' "$PATH" | tr ':' '\n' | awk '!/ / && (/^(\/|\.\/|\.\.\/|~\/)/)')
          if [ -z "$CLEAN_PATH" ]; then
            CLEAN_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          else
            CLEAN_PATH=$(printf '%s\n' "$CLEAN_PATH" | paste -sd: -)
          fi
          printf 'PATH=%s\n' "$CLEAN_PATH" >> "$GITHUB_ENV"

      - name: Set up Docker auth
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.docker_push == 'true' }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build (manual with inputs)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          PROFILE: ${{ inputs.profile }}
          INCLUDE_DOCKER: ${{ inputs.include_docker }}
          ENABLE_PPPOE: ${{ inputs.enable_pppoe }}
          CUSTOM_PACKAGES: ${{ inputs.custom_packages }}
        run: |
          bash build.sh -d

      - name: Build (push with defaults)
        if: ${{ github.event_name == 'push' }}
        env:
          PROFILE: 1024
          INCLUDE_DOCKER: "yes"
          ENABLE_PPPOE: "no"
          CUSTOM_PACKAGES: ""
        run: |
          bash build.sh -d

      - name: Push Docker image
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.docker_push == 'true' }}
        run: |
          docker push immortalwrt-amd64:latest
          docker push immortalwrt-amd64:24.10.3
